// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoL453vuO_zW7CuCjCqfUBfy1cYhmDhOo',
    appId: '1:18880304485:web:58ceaed806258209f1fd8c',
    messagingSenderId: '18880304485',
    projectId: 'iskainan',
    authDomain: 'iskainan.firebaseapp.com',
    storageBucket: 'iskainan.appspot.com',
    measurementId: 'G-S9SSG6HTL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCArOtDbKEmnyJltQPn8V45p4xwykV8NTc',
    appId: '1:18880304485:android:fb5859e4605af06ff1fd8c',
    messagingSenderId: '18880304485',
    projectId: 'iskainan',
    storageBucket: 'iskainan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLNFP5TJPCdgkT34GH9ttZpCXQGb3Lt94',
    appId: '1:18880304485:ios:073595d40147e429f1fd8c',
    messagingSenderId: '18880304485',
    projectId: 'iskainan',
    storageBucket: 'iskainan.appspot.com',
    iosClientId: '18880304485-gm7s6iq50a9t8fe30jdkbv6e34m1umbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.iskainan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLNFP5TJPCdgkT34GH9ttZpCXQGb3Lt94',
    appId: '1:18880304485:ios:073595d40147e429f1fd8c',
    messagingSenderId: '18880304485',
    projectId: 'iskainan',
    storageBucket: 'iskainan.appspot.com',
    iosClientId: '18880304485-gm7s6iq50a9t8fe30jdkbv6e34m1umbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.iskainan',
  );
}
